import Pkg
Pkg.activate("../Packages")

Pkg.add("NLPModels")
Pkg.add("JSOSolvers")
Pkg.add("Plots")
Pkg.add("PyPlot")
Pkg.add("ADNLPModels")
Pkg.add("AmplNLReader")
Pkg.add("JuMP")
Pkg.add("MAT")
Pkg.add("NLPModelsJuMP")
Pkg.add("FileIO")
Pkg.add("Images")
Pkg.add("ImageView")
Pkg.add("LinearOperators")
Pkg.add("Stopping")
Pkg.add("LBFGSB")
Pkg.add("ForwardDiff")
Pkg.add("LinearAlgebra")
Pkg.add("MathProgBase")
Pkg.add("Ipopt")
Pkg.add("NLPModelsIpopt")
